#!/bin/sh -eux

mkdir -p "${SNAP_COMMON}/cookie"

# Create a cookie during installation, otherwise one will be automatically
# generated in /var/lib/rabbitmq (verboten by default) or in $HOME (inaccessible
# by other snaps).
tr -dc A-Za-z0-9 </dev/urandom | head -c 13 > "${SNAP_COMMON}/cookie/.erlang.cookie"
chmod 0400 "${SNAP_COMMON}/cookie/.erlang.cookie"
